name:                domainmodeling
version:             0.1.0.0
github:              "nbardiuk/domainmodeling"
license:             BSD3
author:              "Nazarii Bardiuk"
maintainer:          "nazarii@bardiuk.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nbardiuk/domainmodeling#readme>

dependencies:
- base >= 4.7 && < 5
- semigroups

library:
  source-dirs: src

executables:
  domainmodeling-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - domainmodeling

tests:
  domainmodeling-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - domainmodeling
